### PR TITLE
Support for integrating with existing networking; deployment script fixes for cron and time zones

### LINKED ISSUE #34: Support for virtual network peering
*Transferred from https://github.com/kalalvishal/azure-redcap-paas/issues/40*

### LINKED ISSUE #38: Deploy App Service in P0V3 SKU to ensure scalability
*Transferred from https://github.com/kalalvishal/azure-redcap-paas/issues/50*

### LINKED ISSUE #58: Use environment variable references in database.php
Currently, the deployment script dumps the database connection values in database.php. This means that after deployment, it's not possible to update those values. Moreover, those values are available in plain text in database.php.

We need to use something like `$_ENV['db_username']`.

### LINKED ISSUE #83: Remove Private Endpoint for REDCap dashboard app service
Hi,

We've noticed if we do an nslookup on the public URL created by the Bicep, it goes to a private link resource. This causes issues when trying to access the redcap API from other resources in azure as it thinks it's a private link resource.

After looking into it, it looks like the private endpoint isn't actually being used for anything, and so should be removed to save costs and reduce complexity.

Thanks

### LINKED ISSUE #93: Support for setting time zone for REDCap and cron jobs
In redcap.ini, add
`date.timezone=<<Linux TZ value, e.g., UTC or America/New_York>>`

In /usr/local/etc/php/conf.d/php.ini, replace
`date.timezone=UTC` with the same value as above.

Default will remain UTC.

### PR DESCRIPTION
**Pull request by SvenAelterman**
This update optionally enables specifying an existing Azure virtual network to deploy resources into. 

When setting that parameter value, you must also set the parameter for the resource group ID of existing private DNS zones for blob, Key Vault, MySQL, and App Service. Further, you must also specify the `subnets` parameter to specify the names of existing subnets for private endpoints, MySQL private access, and App Service virtual network integration.

Closes #34, even though this deployment code does not perform the peering. However, the existing virtual network can be peered to other networks before or after the REDCap deployment.

New parameters have been added to the main.bicep to support this:

- `existingVirtualNetworkId`
- `existingPrivateDnsZonesResourceGroupId`
- `subnets`
- `enableAppServicePrivateEndpoint` (closes #83)

Also closes #58.

Also closes #38.

Also closes #93.

### CODE REVIEW

File: scripts/bash/startup.sh [hunk 1]
```diff
@@ -8,13 +8,13 @@ echo "Custom container startup"
...
 
 ####################################################################################
 #
 # Configure REDCap cronjob to run every minute
 #
 ####################################################################################
 
-service cron start
-(crontab -l 2>/dev/null; echo "* * * * * /usr/local/bin/php /home/site/wwwroot/cron.php > /dev/null")|crontab 
+# service cron start
```
Comment (SvenAelterman) [inline scripts/bash/startup.sh:19]: This probably should be re-enabled to ensure cron is configured even after scaling out or deploying a new container.

File: modules/webapp/webapp.bicep [hunk 2]
```diff
@@ -144,10 +150,20 @@ resource webApp 'Microsoft.Web/sites@2022-03-01' = {
           name: 'StorageContainerName'
           value: storageAccountContainerName
         }
+        // END EDOC
         {
           name: 'ENABLE_DYNAMIC_INSTALL'
           value: 'true'
         }
+        {
+          name: 'PRE_BUILD_COMMAND'
```
Comment (SvenAelterman) [inline modules/webapp/webapp.bicep:159]: This needs to be removed because it does not work.

File: modules/webapp/webapp.bicep [hunk 3]
```diff
@@ -144,10 +150,20 @@ resource webApp 'Microsoft.Web/sites@2022-03-01' = {
...
+          value: 'apt-get update -qq && apt-get install default-mysql-client -yqq'
+        }
+        {
+          // HACK: 2024-09-24: svaelter: Re-added to ensure /home/site/ini/redcap.ini and /home/site/ini/extensions.ini gets processed
```
Comment (SvenAelterman) [inline modules/webapp/webapp.bicep:163]: This is required.

**Comment by SvenAelterman** [comment]
@matheuscarboni, @kalalvishal This PR is now ready for your review.
